### ISSUE TITLE
Wrong line numbers after wrap

### ISSUE THREAD

**Issue by steros** [ColdDevil/de.cdhq.eclipse.wordwrap#11]
When activating the wrapping the line numbers are different, every wrapped line gets a new line.
Version is 4.4.2 Linux 64bit

**Comment by ColdDevil** [comment]
Could you post a screenshot? Do you mean the line number ruler is not working properly? In this case you could try starting eclipse with the -clean parameter if you haven't done that yet. :smiley:

**Comment by steros** [comment]
Yeah, "-clean" worked. Can you add this to the docs?

**Comment by ColdDevil** [comment]
Great to hear! Sure, it's in the docs at http://dev.cdhq.de/eclipse/word-wrap/ but I will highlight it more. Seems to be not prominent enough. :wink:

**Comment by steros** [comment]
I meant emphasize the relation of display problems and the possible solution via a "clean" :)

**Comment by ColdDevil** [comment]
Yeah, I guess "-clean" is necessary in any case. I might recommend this as part of the installation process. :wink:
