### ISSUE TITLE
Repository stopped working

### ISSUE THREAD

**Issue by stalker780** [ColdDevil/de.cdhq.eclipse.wordwrap#17]
http://dev.cdhq.de/eclipse/word-wrap/ does not work anymore

I used http://dev.cdhq.de/eclipse/updatesite/luna/ for Eclipse PHP 2019-06 M2 (4.12.0M2) and it worked fine, till I did not decide to reinstall eclipse.

Embedded Word Wrap works only for limited number of file extensions. It does not work in css, js, twig files. Plugin from above repository worked in every editor.

**Comment by ColdDevil** [comment]
Hi @stalker780! Thanks for bringing up the issue. Sorry, I was reconfiguring the domain. It should work again. :)

**Comment by stalker780** [comment]
@ColdDevil, Great to hear this project is still alive! 
Repo works fine now.

Thank you for your work and very useful plugin. Cannot imagine how I would use Eclipse without it.
