### ISSUE TITLE
Line number fix not working on Luna M5

### ISSUE THREAD

**Issue by ghost** [ColdDevil/de.cdhq.eclipse.wordwrap#2]
Aware current release intended for Kepler but thought worth noting the issue in hope its simple to resolve (good time also to say good job on word wrap feature! Thanks)

**Comment by pipelinevp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Erkansukgen, @gusakovm, @devcovato, @Cotex05, @groveshm, @tkasuz, @steezeburger, @milne-dev, @jgh2i, @vimoppa, @Gajanana, @TBSupportChannel, @johncrisostomo, @shivamsinha15, @SteveXCIV, @weirdgiraffe, @Liudaylearn, @chellem, @thorstenhirsch, @isecren, @zkmsg, @devikaja, @bordumb, @gevera, @zephyrus21, @FlashSheridan, @lixiphp, @cinquemb, @kevinweaver, @trubavuong, @lotgyero, @ochudidesterio, @preetidangi21, @agl0809, @emkman99, @sharonite, @dkalford, @yagop, @quadroloop, @theGateW, @codesnakers, @KBirzins, @Pingmin, @guoqing-bit, @shirishkz, @camperos7e3, @xiaowu2333, @vasilia, @ethgallucci, @MikoTurkNode999888liao, @097ADITYA, @jinsley8, @pawelkurzyca, @gtsigner, @pnpolcher, @xxLestadxx, @Sanbingo, @zsevic, @cooljith91112, @ashim-kr-saha, @jzarca01, @sokist, @raphaelcosta, @grzesimaj-74, @alexruco, @emberfarkas, @aryanadi-ic, @nvFede, @triangulair, @zm1445671444, @coutureb, @KishiTheMechanic, @MKamelll, @cmarmulla, @xufengzhu19, @MerkleBoy, @paseaf, @xxxXinh, @masud99r, @lawphotog, @LuiSauter, @Double1996, @m-pedro, @Faiznurullah, @samkenxstream, @Potat-Cat, @Guidosalimbeni, @visualrobots, @tarmo888, @anhskohbo, @NeoMindStd, @AmosAidoo, @Hsu-ken, @alexkubica, @kimgalaxy, @ascender1729, @henriquechagasg, @daveleee, @super117893344pzkmsg, @danieldanielecki, @c00k133, @rockstox, @memez-michalek, @whitecandylee, @dkscott-dev, @ghophp, @mdrame, @mikedotexe, @miguelrevera, @spstar, @faysalhaque, @wanglixuan123, @brsbyrk, @yoratoni, @wh1100717, @nksrentas, @fridaymeng, @S2606, @myhendry, @jletey, @deepakgsrn, @RGHuang, @AlexTroshkin, @lggg123, @baakeydow, @afenotes, @Bandoolu, @smallpotato000, @skrutikov, @pespantelis, @aoooio, @playflycode, @ireade, @firebase007, @throche, @interisti, @PatrickTheStarfish01, @hieundx, @Alexader, @Ganesh-Chavan, @StuckInLoop, @ddtme, @pyaehein, @gabepereira, @joshstow, @rodleviton, @xmuhot, @mevbots
